// Hand-curated navigation tree. Introduction is a single flat link rendered
// directly in base.njk, ahead of this array — a permanent "home" link, not
// a section. Getting started leads this array: everything a fresh server
// admin does exactly once (install the mod, learn the file layout, set the
// handful of settings you configure right away) before anything else. Then
// Content creation — the concept every other page assumes you've already
// read — then Core/Economy/World/Server utilities follow README.md's own
// Key features order, with Guides pulled into their own group for sidebar
// usability, followed by Tooling, For mod developers, Reference. There is
// deliberately no "Server administration" group: on reflection, every page
// that used to live there is either a one-time setup step (→ Getting
// started) or squarely a sub-topic of something else (→ nested below).
// Every group carries a `subtitle` — a one-line hint at what's inside,
// shown as a small second line under the group name (see base.njk/site.css)
// specifically so it's still readable with the group collapsed: a visitor
// scanning for something doesn't have to expand every section first just to
// rule most of them out.
//
// No nav item should be an external link — one entry per YouTube video (the
// original design) meant seven identical-looking rows for one collection,
// and no internal home for any of them. They're consolidated onto a single
// page, guides/video-guides.md, grouped by author, linked from Guides as one
// normal internal entry instead. The `external`/target=_blank handling in
// base.njk stays as reusable infrastructure even with nothing using it right
// now — cheap to keep, and it's the obvious tool if an external nav link is
// ever genuinely warranted again.
//
// An item may carry `children` — a third nesting level for pages that are
// squarely a sub-topic of another page rather than a peer entry in the
// group, e.g. Quest Profiles/Quest Events under Quests. The parent stays a
// real link to its own page; children render collapsed by default (see
// scripts/nav-collapse.js) unless the visitor is already on the parent or
// one of its children, expanding automatically so they don't lose context.
// Every grouping below is backed by that page's own "## Related" section in
// the source .md, not a guess — e.g. npc-system.md links Marketplace
// Hammer/Saved NPCs/Random NPC Speech as directly related, so those nest
// under NPC system here. Custom assets nests under Prefabs and text markup
// since that page's own Related section already treats it as the page a
// reader goes to next; Hot reload nests under Config file syntax for the
// same reason (its own Related section points there, for spotting the kind
// of formatting mistake that stops a reload from picking up your change).
// Localization keys nests under Synced Localizer rather than sitting in
// Reference or Getting started: it isn't a settings file you fill in once
// (unlike Server/Client config), it's a lookup table you search whenever
// you want to reword one specific string, which could be during initial
// setup or a year later — and synced-localizer.md's own Related section
// already treats it as the reference for the labels it lets you override.
//
// Mail/Feedback/Chat nest under Server config/Client config as anchor
// links (`#mail`, `#feedback`, `#kg-chat`) rather than getting their own
// pages — they're just settings inside those two files, not separate
// features. Chat's anchor is a real heading (`## [KG Chat]`) already
// generated by IdAttributePlugin; Mail and Feedback are single rows inside
// Server config's one big Settings table, so those two got a hand-placed
// empty `<a id="...">` right in the row instead of a heading of their
// own. scripts/anchor-highlight.js scrolls to and flashes whatever the
// link's #id resolves to (the whole table row, if the id sits inside one)
// so landing mid-table isn't disorienting.
export default [
  {
    title: "Getting started",
    subtitle: "install, files & first settings",
    items: [
      { title: "Installation", href: "/setup/installation/" },
      { title: "File structure", href: "/setup/file-structure/" },
      {
        title: "Server config",
        href: "/setup/server-config/",
        children: [
          { title: "Mail", href: "/setup/server-config/#mail" },
          { title: "Feedback", href: "/setup/server-config/#feedback" },
        ],
      },
      {
        title: "Client config",
        href: "/setup/client-config/",
        children: [{ title: "Chat", href: "/setup/client-config/#kg-chat" }],
      },
    ],
  },
  {
    title: "Content creation",
    subtitle: "syntax, profiles, conditions & commands",
    items: [
      { title: "Content creation", href: "/concepts/content-creation/" },
      {
        title: "Config file syntax",
        href: "/concepts/config-syntax/",
        children: [{ title: "Hot reload", href: "/setup/hot-reload/" }],
      },
      { title: "Profiles", href: "/concepts/profiles/" },
      { title: "Conditions", href: "/concepts/conditions/" },
      { title: "Commands", href: "/concepts/commands/" },
      {
        title: "Prefabs and text markup",
        href: "/concepts/prefabs-and-assets/",
        children: [{ title: "Custom assets", href: "/assets/custom-assets/" }],
      },
      { title: "Scheduled configs", href: "/concepts/time-windows/" },
    ],
  },
  {
    title: "Core",
    subtitle: "NPCs, quests, dialogue & factions",
    items: [
      {
        title: "NPC system",
        href: "/npc/npc-system/",
        children: [
          { title: "Marketplace Hammer", href: "/npc/marketplace-hammer/" },
          { title: "Saved NPCs", href: "/configs/saved-npcs/" },
          { title: "Random NPC Speech", href: "/configs/random-npc-speech/" },
        ],
      },
      {
        title: "Quests",
        href: "/configs/quests/",
        children: [
          { title: "Quest Profiles", href: "/configs/quest-profiles/" },
          { title: "Quest Events", href: "/configs/quest-events/" },
        ],
      },
      {
        title: "Dialogues",
        href: "/configs/dialogues/",
        children: [{ title: "Custom Spawn Data", href: "/configs/custom-spawn-data/" }],
      },
      { title: "Factions", href: "/configs/factions/" },
    ],
  },
  {
    title: "Economy",
    subtitle: "shops, currency & rewards",
    items: [
      { title: "Traders", href: "/configs/traders/" },
      { title: "Bankers", href: "/configs/bankers/" },
      { title: "Gamblers", href: "/configs/gamblers/" },
      {
        title: "Buffers",
        href: "/configs/buffers/",
        children: [{ title: "Buffer Profiles", href: "/configs/buffer-profiles/" }],
      },
      { title: "Transmogrification", href: "/configs/transmogrification/" },
    ],
  },
  {
    title: "World",
    subtitle: "zones, travel & server info",
    items: [
      { title: "Server Info", href: "/configs/server-infos/" },
      { title: "Teleporters", href: "/configs/teleporters/" },
      { title: "Territories", href: "/configs/territories/" },
    ],
  },
  {
    title: "Server utilities & extras",
    subtitle: "tags, webhooks, commands & more",
    items: [
      { title: "Player Tags", href: "/configs/player-tags/" },
      {
        title: "Synced Localizer",
        href: "/configs/synced-localizer/",
        children: [{ title: "Localization keys", href: "/reference/localization-keys/" }],
      },
      { title: "Console commands", href: "/setup/console-commands/" },
      { title: "Distanced UI", href: "/configs/distanced-ui/" },
      { title: "Discord Webhooks", href: "/configs/discord-webhooks/" },
      { title: "Leaderboard Achievements", href: "/configs/leaderboard-achievements/" },
    ],
  },
  {
    title: "Guides",
    subtitle: "walkthroughs & video tutorials",
    items: [
      { title: "Your first quest", href: "/guides/first-quest/" },
      { title: "Quest chains", href: "/guides/quest-chain/" },
      { title: "A branching dialogue tree", href: "/guides/dialogue-tree/" },
      { title: "Dialogue patterns", href: "/guides/dialogue-patterns/" },
      { title: "Tracking player state", href: "/guides/tracking-player-state/" },
      { title: "Shops, currency, and taxes", href: "/guides/shop-and-economy/" },
      { title: "Setting up a territory", href: "/guides/territory-setup/" },
      { title: "Video guides", href: "/guides/video-guides/" },
    ],
  },
  {
    title: "Tooling",
    subtitle: "third-party editors & tools",
    items: [
      { title: "VS Code extensions", href: "/tooling/vscode-extension/" },
      { title: "Coming soon", href: "/tooling/coming-soon/" },
    ],
  },
  {
    title: "For mod developers",
    subtitle: "what other mods can access",
    items: [{ title: "Integrating with this mod", href: "/api/modder-api/" }],
  },
  {
    title: "Reference",
    subtitle: "changelog, migrations & known gaps",
    items: [
      { title: "Changelog", href: "/reference/changelog/" },
      { title: "Migrations", href: "/reference/migrations/" },
      { title: "Known gaps", href: "/reference/known-gaps/" },
    ],
  },
];
